book: /root/bookstore/bookPhoto/
user: /root/bookstore/userPhoto/
server:
  port: 9010
spring:
  mvc:
    static-path-pattern: /photo/**
  resources:
    static-locations: file:${book, user}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.93.53.85:3306/bookstore?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Wqx981127@